import "oaidl.idl";
import "ocidl.idl";

[uuid(B1346A74-9611-4f57-AA77-08EEE4E2E8CE)]
library ServiceTest{
    importlib("stdole32.tlb");


    typedef [uuid(E1573228-8281-418E-930E-071D5C7622F9)]
    struct ServiceInfo_ 
    {
        BSTR serviceName;
    }ServiceInfo_;
}


