
[uuid(C1D3A8C0-A4AA-11D0-819C-00A0C90FFFC3)]
library udttest
{
   typedef
   [
   uuid(C21871A0-33EB-11D4-A13A-BE2573A1120F),
   version(1.0),
   helpstring("A Demo UDT variable for VB projects")
   ]
   struct UDTVariable {
   [helpstring("Special case variant")] VARIANT Special;
   [helpstring("Name of the variable")] BSTR Name;
   [helpstring("Value of the variable")] long Value;
   } UDTVariable;
};